language: objective-c
env:
    matrix:
    - XCODE_SCHEME=TwitterAPITests-iOS XCODE_SDK=iphonesimulator
    - XCODE_SCHEME=TwitterAPITests-Mac XCODE_SDK=macosx
before_install:
    - brew update
    - brew install carthage
    - carthage bootstrap --verbose
script: xctool -project TwitterAPI.xcodeproj -scheme $XCODE_SCHEME -sdk $XCODE_SDK -configuration Release build test
osx_image: xcode7
