language: objective-c
env:
    matrix:
    - XCODE_SCHEME="TwitterAPI iOS Tests" XCODE_SDK=iphonesimulator
    - XCODE_SCHEME="TwitterAPI Mac Tests" XCODE_SDK=macosx
before_script:
    - ./scripts/add-key.sh
    - brew update
    - brew install carthage
    - carthage bootstrap --configuration Debug --verbose
script: xctool -project TwitterAPI.xcodeproj -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -configuration Release build test
after_script:
    - ./scripts/remove-key.sh
osx_image: xcode7
